FROM node:12.10-alpine

ENV WEBPACK_DEV_SERVER_PORT 8080

RUN mkdir /assets

WORKDIR /assets

COPY assets/package.json assets/yarn.lock ./

RUN npm install -g yarn

EXPOSE $WEBPACK_DEV_SERVER_PORT

CMD ["yarn", "run", "start:dev"]
