FROM ruby:2.6.4-alpine3.10

ENV APP_HOME /spritesheet
ENV BUNDLER_VERSION 2.0.2
ENV APP_PORT 3000
ENV RACK_ENV development

RUN apk add --update build-base ghostscript ghostscript-fonts imagemagick

RUN mkdir $APP_HOME

WORKDIR $APP_HOME

COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN gem install bundler -v $BUNDLER_VERSION && bundle install

COPY . $APP_HOME

EXPOSE $APP_PORT

CMD ["bundle", "exec", "puma", "config.ru", "-C", "config/puma.rb"]
