version: "3"

services:
  sinatra:
    build:
      context: "."
      dockerfile: "./Dockerfile.sinatra"
    volumes:
      - ".:/spritesheet"
    ports:
      - "3000:3000"
    command: "bundle exec puma config.ru -C config/puma.rb"
  webpack:
    build:
      context: "."
      dockerfile: "./Dockerfile.webpack"
    volumes:
      - "./assets:/assets"
      - "node_modules:/assets/node_modules"
    ports:
      - "8080:8080"
    command: "yarn run start:dev"

volumes:
  node_modules:
